### ISSUE TITLE
FVTT Version 10 Build 284 Compatibility

### ISSUE THREAD

**Issue by CharlesHunter** [SvenWerlen/moulinette-core#47]
Upon loading FVTT with Moulinette-Core enabled, the following exception is thrown.
```TypeError: Cannot set property active of #<InteractionLayer> which has only a getter
[Detected 1 package: moulinette-core]
    at new MoulinetteLayer (moulinette-layer.js:7:17)
    at #createLayers (foundry.js:28388:38)
    at new BaseCanvasMixin (foundry.js:28362:39)
    at new PrimaryCanvasGroup (foundry.js:38810:5)
    at #createGroups (foundry.js:23236:21)
    at #createGroups (foundry.js:23240:25)
    at #createGroups (foundry.js:23240:25)
    at Canvas.initialize (foundry.js:23064:23)
    at Game.initializeCanvas (foundry.js:7908:19)
    at async Game.setupGame (foundry.js:7747:5)
    at async Game._initializeGameView (foundry.js:8820:5)
    at async Game.initialize (foundry.js:7630:5)```

**Comment by SvenWerlen** [comment]
Thank you for reporting it. 
I'm planning to release v10 compatible version this week-end (September 3-4)

**Comment by SvenWerlen** [comment]
Moulinette modules are now officially supported for FoundryVTT v10. 
I also updated the versioning to match FVTT. New versions are now 10.0.0.
Be careful when upgrading. I tested as much as I could but I probably missed some edge use cases. Feel free to report the issues on : https://github.com/SvenWerlen/moulinette-core/issues
