### ISSUE TITLE
TypeError: Failed to render WebGL canvas. Cannot set property active of #<InteractionLayer> which has only a getter

### ISSUE THREAD

**Issue by matt-duffy** [SvenWerlen/moulinette-core#53]
In a world that I have upgraded to 10.286 (running the DnD v2.0.2 system) on any existing scenes or any new scene I create, I get this error when I have Moulinette Core (and only Moulinette Core) enabled as a module, it stops the canvas from rendering:

```
TypeError: Failed to render WebGL canvas. Cannot set property active of #<InteractionLayer> which has only a getter
    at new MoulinetteLayer (moulinette-layer.js:7:17)
    at #createLayers (foundry.js:27064:38)
    at new BaseCanvasMixin (foundry.js:27038:39)
    at new PrimaryCanvasGroup (foundry.js:38961:5)
    at #createGroups (foundry.js:23284:21)
    at #createGroups (foundry.js:23288:25)
    at #createGroups (foundry.js:23288:25)
    at Canvas.initialize (foundry.js:23112:23)
    at Game.initializeCanvas (foundry.js:7993:19)
    at async Game.setupGame (foundry.js:7837:5)
```

However, if I create a brand-new world (using the same system) and enable Moulinette Core I don't get this error.

**Comment by SvenWerlen** [comment]
According to my investigation (thanks to the stacktrace), you're still on moulinette-core `4.10` which only supports FVTT v.9.
Please make sure that all moulinette modules have version `10.0.1` or more.
Feel free to reopen this issue if needed.

**Comment by matt-duffy** [comment]
Ah OK, I think there's something odd going on with the module update process for the Moulinette modules then, I tried updating modules multiple times and it never updated them to the latest version, I had to uninstall all the moulinette modules and reinstall to get the correct version
